[package]
name = "owos"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-owos.json"

[unstable]
build-std = ["core", "compiler_builtins"]

[dependencies]
bootloader = "0.9"
spin = "0.10.0"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.5"
features = ["spin_no_std"]
