[package]
name = "owos"
version = "0.3.1"
edition = "2024"

[dependencies]
log = "0.4"
pc-keyboard = "0.8.0"
uefi = "0.35.0"
uefi-raw = "0.11.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
