[package]
name = "owos"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-owos.json"

[unstable]
build-std = ["core", "compiler_builtins"]

[dependencies]
bootloader = "0.9"
