[package]
name = "owos"
version = "0.3.4"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
log = "0.4"
pc-keyboard = "0.8.0"
uefi = "0.35.0"
uefi-graphics2 = "0.5.0"
uefi-raw = "0.11.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
